// MICRO 18 — Daily PIB Fetch + Strict 20/day Limit Tests
"use strict";const path=require("path"),fs=require("fs");const root=path.resolve(__dirname,"..");
var P=0,F=0;function assert(c,n,d){if(c){P++;console.log("  PASS: "+n);}else{F++;console.log("  FAIL: "+n+(d?" — "+d:""));} }
function sec(t){console.log("\n--- "+t+" ---");}
var pib=require(path.join(root,"admin","sources","pib-fetcher.js"));
var dailyScript=path.join(root,"build","scripts","pib-daily-fetch.js");
// Mirrors the strict applyCategoryLimits from pib-daily-fetch.js
function lim(items,mc,mt){var counts={};["Government","Documents","Business","Money","Education","needs_manual_categorization"].forEach(function(c){counts[c]=0;});var ta=0,a=[],r=[];for(var i=0;i<items.length;i++){var it=items[i],cat=it.primary_category||"needs_manual_categorization";if(counts[cat]===undefined)counts[cat]=0;if(ta>=mt){r.push(it);continue;}if(cat!=="needs_manual_categorization"&&counts[cat]>=mc){r.push(it);continue;}counts[cat]++;ta++;a.push(it);}return{accepted:a,rejected:r,counts:counts,totalAccepted:ta};}
sec("1. Gov max 4");var g4=[];for(var i=0;i<4;i++)g4.push({title:"G"+i,primary_category:"Government"});var r1=lim(g4,4,20);assert(r1.accepted.length===4,"4 Gov accepted");assert(r1.rejected.length===0,"0 rejected");
sec("2. Doc max 4");var d4=[];for(var i=0;i<4;i++)d4.push({title:"D"+i,primary_category:"Documents"});var r2=lim(d4,4,20);assert(r2.accepted.length===4,"4 Doc accepted");assert(r2.rejected.length===0,"0 rejected");
sec("3. Biz max 4");var b4=[];for(var i=0;i<4;i++)b4.push({title:"B"+i,primary_category:"Business"});var r3=lim(b4,4,20);assert(r3.accepted.length===4,"4 Biz accepted");
sec("4. Money max 4");var m4=[];for(var i=0;i<4;i++)m4.push({title:"M"+i,primary_category:"Money"});var r4=lim(m4,4,20);assert(r4.accepted.length===4,"4 Money accepted");
sec("5. Edu max 4");var e4=[];for(var i=0;i<4;i++)e4.push({title:"E"+i,primary_category:"Education"});var r5=lim(e4,4,20);assert(r5.accepted.length===4,"4 Edu accepted");
sec("6. 4+4+4+4+4=20");var all=[];["Government","Documents","Business","Money","Education"].forEach(function(c){for(var i=0;i<4;i++)all.push({title:c+i,primary_category:c});});var r6=lim(all,4,20);assert(r6.accepted.length===20,"20 total");assert(r6.rejected.length===0,"0 rejected");
sec("7. Manual NOT unlimited");var mn=[];for(var i=0;i<10;i++)mn.push({title:"M"+i,primary_category:"needs_manual_categorization"});var r7=lim(mn,4,20);assert(r7.accepted.length===10,"10 accepted (10 < 20 cap)");assert(r7.rejected.length===0,"0 rejected (within 20 cap)");assert(r7.totalAccepted===10,"totalAccepted=10");
sec("8. 20 manual=max 20");var m20=[];for(var i=0;i<20;i++)m20.push({title:"M"+i,primary_category:"needs_manual_categorization"});var r8=lim(m20,4,20);assert(r8.accepted.length===20,"20 accepted");assert(r8.rejected.length===0,"0 rejected");
sec("9. 21 items cannot pass");var m21=[];for(var i=0;i<21;i++)m21.push({title:"M"+i,primary_category:"needs_manual_categorization"});var r9=lim(m21,4,20);assert(r9.accepted.length===20,"20 accepted");assert(r9.rejected.length===1,"1 rejected");assert(r9.totalAccepted===20,"totalAccepted=20");
sec("10. Mixed 5Gov+5others");var mx=[{title:"G1",primary_category:"Government"},{title:"G2",primary_category:"Government"},{title:"G3",primary_category:"Government"},{title:"G4",primary_category:"Government"},{title:"G5",primary_category:"Government"},{title:"D1",primary_category:"Documents"},{title:"B1",primary_category:"Business"},{title:"M1",primary_category:"Money"},{title:"E1",primary_category:"Education"},{title:"X1",primary_category:"needs_manual_categorization"}];var r10=lim(mx,4,20);assert(r10.accepted.length===9,"9 accepted");assert(r10.rejected.length===1,"1 Gov rejected");assert(r10.counts.Government===4,"Gov=4");assert(r10.totalAccepted===9,"total=9");
sec("11. Mixed=20 exact");var mix20=[{title:"G1",primary_category:"Government"},{title:"G2",primary_category:"Government"},{title:"G3",primary_category:"Government"},{title:"G4",primary_category:"Government"},{title:"D1",primary_category:"Documents"},{title:"D2",primary_category:"Documents"},{title:"D3",primary_category:"Documents"},{title:"D4",primary_category:"Documents"},{title:"B1",primary_category:"Business"},{title:"B2",primary_category:"Business"},{title:"B3",primary_category:"Business"},{title:"B4",primary_category:"Business"},{title:"M1",primary_category:"Money"},{title:"M2",primary_category:"Money"},{title:"M3",primary_category:"Money"},{title:"M4",primary_category:"Money"},{title:"E1",primary_category:"Education"},{title:"E2",primary_category:"Education"},{title:"X1",primary_category:"needs_manual_categorization"},{title:"X2",primary_category:"needs_manual_categorization"}];var r11=lim(mix20,4,20);assert(r11.accepted.length===20,"20 accepted");assert(r11.rejected.length===0,"0 rejected");
sec("12. 21st item rejected");var mix21=mix20.concat([{title:"X3",primary_category:"needs_manual_categorization"}]);var r12=lim(mix21,4,20);assert(r12.accepted.length===20,"20 accepted");assert(r12.rejected.length===1,"1 rejected");assert(r12.rejected[0].primary_category==="needs_manual_categorization","Rejected is manual");
sec("13. Zero releases");var r13=lim([],4,20);assert(r13.accepted.length===0,"0 accepted");
sec("14. 10 in one cat");var ten=[];for(var i=0;i<10;i++)ten.push({title:"B"+i,primary_category:"Business"});var r14=lim(ten,4,20);assert(r14.accepted.length===4,"4 accepted");assert(r14.rejected.length===6,"6 rejected");
sec("15. Script exists");assert(fs.existsSync(dailyScript),"pib-daily-fetch.js exists");
sec("16. PIB fetcher");var ls='<h3 class="font104">Min</h3><a title="Rel" href="/PressReleaseDetail.aspx?PRID=12345" target="_blank">Rel</a>';var p=pib.parseListingPage(ls);assert(p.ok,"Listing ok");assert(p.releases.length===1,"1 found");
sec("17. Classification");var c=pib.classifyCategory("Government scheme yojana","Cabinet approved the scheme for farmers kisan subsidy");assert(c.primary_category==="Government","Gov class");
sec("18. Dist exists");assert(fs.existsSync(path.join(root,"dist")),"dist/ exists");
sec("19. Build script");assert(fs.existsSync(path.join(root,"build","build.js")),"build.js exists");
sec("20. Scheduler config exists");assert(fs.existsSync(path.join(root,"build","scripts","pib-scheduler-setup.bat"))||fs.existsSync(path.join(root,"build","scripts","pib-scheduler-setup.ps1")),"Scheduler setup script exists");
function finish(){console.log("\n========================================\nMICRO 18 TEST SUMMARY\n========================================\nPassed: "+P+"\nFailed: "+F+"\n========================================");process.exit(F>0?1:0);}
finish();
